repos:
  - repo: local
    hooks:
      - id: format
        name: format
        entry: hatch run style:fmt
        language: system
        pass_filenames: false
        verbose: true
        files: \.(py)$
